version: '3'
services:
  redis-master:
    container_name: redis-master
    image: redis:latest
    ports:
      - "6379:6379"
  redis-slave:
    container_name: redis-slave
    image: redis:latest
    ports:
      - "6479:6379"
    command: redis-server --slaveof redis-master 6379
